import type { Habit, Project, Task } from './types'

export const initialTasks: Task[] = [
  {
    id: 1,
    title: '梳理本周重点和时间安排',
    project: '工作规划',
    category: '工作',
    color: '#496d5b',
    priority: 'high',
    start: '09:30',
    end: '10:20',
    duration: 50,
    completed: true,
  },
  {
    id: 2,
    title: '完成课程第三章笔记',
    project: '前端进阶',
    category: '学习',
    color: '#b96552',
    priority: 'high',
    start: '11:00',
    end: '12:00',
    duration: 60,
    completed: false,
  },
  {
    id: 3,
    title: '力量训练 · 下肢',
    project: '体能恢复',
    category: '健康',
    color: '#58748f',
    priority: 'medium',
    start: '15:30',
    end: '16:15',
    duration: 45,
    completed: false,
  },
  {
    id: 4,
    title: '阅读 30 页',
    project: '年度阅读',
    category: '成长',
    color: '#a1843e',
    priority: 'low',
    start: '19:00',
    end: '19:30',
    duration: 30,
    completed: false,
  },
  {
    id: 5,
    title: '整理保险文件',
    project: '生活事务',
    category: '生活',
    color: '#7a6b87',
    priority: 'medium',
    due: '今天 21:00',
    duration: 20,
    completed: false,
    unscheduled: true,
  },
  {
    id: 6,
    title: '预约牙医复诊',
    project: '生活事务',
    category: '健康',
    color: '#58748f',
    priority: 'low',
    due: '明天',
    duration: 10,
    completed: false,
    unscheduled: true,
  },
]

export const initialHabits: Habit[] = [
  {
    id: 1,
    name: '晨间拉伸',
    detail: '每天 · 10 分钟',
    color: '#496d5b',
    streak: 12,
    checked: [true, true, true, true, true, false, false],
  },
  {
    id: 2,
    name: '力量训练',
    detail: '每周 3 次',
    color: '#b96552',
    streak: 4,
    checked: [true, false, true, false, false, false, false],
  },
  {
    id: 3,
    name: '阅读',
    detail: '每天 · 30 页',
    color: '#a1843e',
    streak: 8,
    checked: [true, true, true, true, false, false, false],
  },
  {
    id: 4,
    name: '零点前入睡',
    detail: '周日至周四',
    color: '#58748f',
    streak: 3,
    checked: [true, true, false, true, false, false, false],
  },
]

export const projects: Project[] = [
  {
    id: 1,
    title: '前端进阶课程',
    area: '学习成长',
    color: '#b96552',
    progress: 62,
    due: '9 月 15 日',
    currentStage: '组件与状态管理',
    completedTasks: 13,
    totalTasks: 21,
    stages: ['基础回顾', '组件与状态管理', '实战项目', '复盘'],
  },
  {
    id: 2,
    title: '体能恢复计划',
    area: '健康',
    color: '#496d5b',
    progress: 44,
    due: '10 月 1 日',
    currentStage: '建立训练节奏',
    completedTasks: 8,
    totalTasks: 18,
    stages: ['评估', '建立训练节奏', '增加强度', '稳定保持'],
  },
  {
    id: 3,
    title: '年度阅读清单',
    area: '个人成长',
    color: '#a1843e',
    progress: 35,
    due: '12 月 31 日',
    currentStage: '第三季度书单',
    completedTasks: 7,
    totalTasks: 20,
    stages: ['上半年', '第三季度书单', '第四季度书单', '年度回顾'],
  },
]

export const weekDays = ['一', '二', '三', '四', '五', '六', '日']
